'use client';
import Image from 'next/image';
import { FormEvent, useEffect, useState } from 'react';

const services = [
  {n:'01', t:'Contabilidade', d:'Organização e registo rigoroso das operações para transformar a contabilidade numa ferramenta de gestão.', items:['Recuperação, classificação e lançamento contabilístico','Reconciliações bancárias e controlo do imobilizado','Balanço, balancetes, resultados e fluxos de caixa','Declarações mensais e apuramento anual']},
  {n:'02', t:'Fiscalidade', d:'Cumprimento fiscal seguro, regularização e acompanhamento permanente perante AGT e INSS.', items:['Apuramento e liquidação de IRT, IVA, IPU, Selo e INSS','Regimes do IVA e submissão do ficheiro SAFT','Certidão de Conformidade Tributária','Contencioso, notificações e inspeções tributárias']},
  {n:'03', t:'Consultoria Financeira', d:'Leitura clara do desempenho para apoiar decisões, rentabilidade e crescimento sustentável.', items:['Análise de custos e estrutura de despesas','Organização e projeção do fluxo de caixa','Planeamento financeiro e orçamentos','Análise de rentabilidade e apoio à decisão']},
  {n:'04', t:'Formação On-job', d:'Capacitação prática, integrada no contexto real da organização e das suas equipas.', items:['Contabilidade aplicada','Controlo interno','Auditoria','Aprendizagem contínua no posto de trabalho']},
];
const sectors=['Comércio','Lojas e minimercados','Farmácias','Consultórios médicos','Consultoria','Colégios','Construção','Restauração','Moda'];
const slides=[
 {src:'/slide-luanda.webp',alt:'Baía e marginal de Luanda',label:'Luanda, Angola',copy:'Ao lado das empresas que constroem o futuro.'},
 {src:'/slide-minfin.webp',alt:'Edifício do Ministério das Finanças em Luanda',label:'Rigor institucional',copy:'Cumprimento, confiança e orientação segura.'},
 {src:'/slide-agt.webp',alt:'Atendimento na Administração Geral Tributária',label:'Proximidade fiscal',copy:'Acompanhamento que simplifica cada obrigação.'},
];

export default function Home(){
 const [menu,setMenu]=useState(false); const [active,setActive]=useState(0); const [slide,setSlide]=useState(0);
 useEffect(()=>{const timer=window.setInterval(()=>setSlide(s=>(s+1)%slides.length),5500);return()=>window.clearInterval(timer)},[]);
 const close=()=>setMenu(false);
 const sendWhatsApp=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const message=`Olá, Valory!%0A%0A*Nome / Empresa:* ${encodeURIComponent(String(data.get('Nome')||''))}%0A*Contacto:* ${encodeURIComponent(String(data.get('Contacto')||''))}%0A*Interesse:* ${encodeURIComponent(String(data.get('Interesse')||''))}%0A*Mensagem:* ${encodeURIComponent(String(data.get('Mensagem')||''))}`;window.open(`https://wa.me/244941098302?text=${message}`,'_blank','noopener,noreferrer')};
 return <main>
  <header className="site-header"><a className="brand" href="#inicio" onClick={close} aria-label="Valory — Início"><Image src="/logo-transparent.png" alt="Valory" width={370} height={210} priority /></a><nav className={menu?'open':''} aria-label="Navegação principal"><a onClick={close} href="#sobre">Sobre</a><a onClick={close} href="#servicos">Serviços</a><a onClick={close} href="#entregaveis">Entregáveis</a><a onClick={close} href="#equipa">Equipa</a><a onClick={close} href="#clientes">Clientes</a><a onClick={close} href="#recursos">FAQ</a><a onClick={close} href="#contactos">Contactos</a></nav><a className="button button-small" href="#contactos">Pedir proposta</a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Abrir menu" aria-expanded={menu}>{menu?'×':'☰'}</button></header>
  <section className="hero" id="inicio"><div className="hero-copy reveal"><p className="eyebrow">Contabilidade · Fiscalidade · Consultoria</p><h1>Decisões mais seguras começam com contas bem cuidadas.</h1><p className="lede">Apoiamos empresas angolanas a organizar, cumprir e crescer com informação financeira clara e acompanhamento próximo.</p><div className="hero-actions"><a className="button" href="#contactos">Solicitar diagnóstico gratuito <span>↗</span></a><a className="text-link" href="#servicos">Conhecer os serviços <span>↓</span></a></div></div><div className="hero-panel"><span className="panel-kicker">Mais de</span><strong>10 anos</strong><span>de experiência no mercado</span><div className="panel-rule"/><p>Rigor técnico, proximidade e informação útil para a gestão.</p></div></section>
  <section className="visual-story" aria-label="Angola e o contexto institucional da Valory"><div className="slides">{slides.map((item,i)=><article className={`slide ${slide===i?'current':''}`} key={item.src} aria-hidden={slide!==i}><Image src={item.src} alt={item.alt} fill sizes="100vw" priority={i===0}/><div className="slide-shade"/><div className="slide-caption"><span>{String(i+1).padStart(2,'0')} / 03</span><p>{item.label}</p><h2>{item.copy}</h2></div></article>)}</div><div className="slide-controls"><button onClick={()=>setSlide((slide-1+slides.length)%slides.length)} aria-label="Imagem anterior">←</button><div>{slides.map((_,i)=><button key={i} className={slide===i?'active':''} onClick={()=>setSlide(i)} aria-label={`Ver imagem ${i+1}`}/>)}</div><button onClick={()=>setSlide((slide+1)%slides.length)} aria-label="Imagem seguinte">→</button></div></section>
  <section className="manifesto" id="sobre"><div><p className="eyebrow">Sobre a Valory</p><h2>Contabilidade que acrescenta valor ao seu negócio.</h2></div><div className="about-copy"><p>A Valory, Lda é uma empresa de direito angolano especializada em contabilidade, consultoria fiscal, consultoria financeira e formação. Trabalhamos com micro, pequenas e médias empresas na sua organização, crescimento e sustentabilidade.</p><p>A nossa missão é apoiar a gestão eficiente dos recursos e o cumprimento das obrigações fiscais com rigor técnico, ética e profissionalismo.</p><div className="values"><span>Confidencialidade</span><span>Competência</span><span>Rigor e transparência</span><span>Compromisso com o cliente</span></div></div></section>
  <section className="services" id="servicos"><div className="section-head"><p className="eyebrow">O que fazemos</p><h2>Soluções sólidas para cada fase da empresa.</h2></div><div className="service-layout"><div className="service-tabs" role="tablist">{services.map((s,i)=><button key={s.t} className={active===i?'active':''} onClick={()=>setActive(i)} role="tab" aria-selected={active===i}><span>{s.n}</span>{s.t}<b>↗</b></button>)}</div><div className="service-detail" role="tabpanel"><p>{services[active].d}</p><ul>{services[active].items.map(x=><li key={x}>{x}</li>)}</ul><a href="#contactos" className="text-link">Falar com um consultor <span>↗</span></a></div></div><div className="more-services"><span>Outros serviços</span><p>Processamento de salários · Emissão de facturas certificadas · Criação de empresas · Cadastro no Instituto de Contratação Pública</p></div></section>
  <section className="deliverables" id="entregaveis"><div className="section-head light"><p className="eyebrow">Acompanhamento contínuo</p><h2>Informação pronta no momento certo.</h2></div><div className="delivery-grid"><article><span>Todos os meses</span><ul><li>Diários de caixa classificados e consolidados</li><li>Impostos lançados e classificados em PRIMAVERA</li><li>Reconhecimento de facturação, retenções, IVA e Selo</li><li>Custos com pessoal, IRT e INSS</li><li>Balancete mensal</li></ul></article><article><span>No fecho anual</span><ul><li>Balanço e demonstração de resultados</li><li>Mapa de amortizações e reintegrações</li><li>Balancetes analítico e final</li><li>Relatório de contas e Modelo 1</li><li>Emissão da CCT</li></ul></article></div></section>
  <section className="team" id="equipa"><div className="section-head"><p className="eyebrow">Equipa e credenciais</p><h2>Experiência que cresce com cada desafio.</h2><p>A equipa integra técnicos médios e superiores de contabilidade e fiscalidade, profissionais experientes e recém-formados, numa cultura de aprendizagem contínua. A Valory trabalha também com técnicos credenciados pela OCPCA.</p></div><div className="team-grid"><article className="profile lead"><div className="avatar"><Image src="/team-03.webp" alt="Daniel Silva, Direção Técnica da Valory" fill sizes="(max-width: 620px) 100vw, (max-width: 950px) 50vw, 33vw"/></div><small>Direção Técnica</small><h3>Daniel Silva</h3><p>Supervisão contabilística · Fiscalidade · Controlo interno · Relato financeiro</p><div className="credential credential-stack"><strong>OCPCA</strong><span>N.º 0000/2026 · número demonstrativo</span></div></article><article className="profile"><div className="avatar"><Image src="/team-02.webp" alt="Lufuankenda Panzo, Consultoria da Valory" fill sizes="(max-width: 620px) 100vw, (max-width: 950px) 50vw, 33vw"/></div><small>Consultoria</small><h3>Lufuankenda Panzo</h3><p>Planeamento financeiro · Análise de custos · Orçamentos · Apoio à decisão</p><div className="credential credential-stack"><strong>Certificações adequadas à função</strong><span>Planeamento e Análise Financeira · Gestão Orçamental · Análise de Custos</span><em>Conteúdo provisório — a confirmar</em></div></article><article className="profile"><div className="avatar"><Image src="/team-01.webp" alt="Lukanu Nzaji, Contabilidade e Formação da Valory" fill sizes="(max-width: 620px) 100vw, (max-width: 950px) 50vw, 33vw"/></div><small>Contabilidade e formação</small><h3>Lukanu Nzaji</h3><p>Registos contabilísticos · PRIMAVERA · Formação On-job · Processamento salarial</p><div className="credential credential-stack"><strong>Certificações adequadas à função</strong><span>Contabilidade Aplicada · Formação de Formadores · PRIMAVERA e Processamento Salarial</span><em>Conteúdo provisório — a confirmar</em></div></article></div><p className="placeholder-note">O número OCPCA apresentado é demonstrativo. Certificações e credenciais individuais devem ser substituídas após confirmação documental.</p></section>
  <section className="clients" id="clientes"><div className="section-head"><p className="eyebrow">Clientes e parceiros</p><h2>Proximidade com negócios de vários sectores.</h2><p>Apoiamos micro, pequenas e médias empresas, com volumes mensais de facturação desde 1.000.000 Kz até valores superiores a 10.000.000 Kz.</p></div><div className="sector-grid">{sectors.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}</div>)}</div><div className="partners"><div className="partners-title"><p className="eyebrow">Parceiros</p><h3>Instituições de referência</h3></div><div className="partner-logos"><div><Image src="/partner-agt.png" alt="AGT — Administração Geral Tributária" width={420} height={260}/><span>AGT</span></div><div><Image src="/partner-inss.png" alt="INSS — Instituto Nacional de Segurança Social" width={420} height={260}/><span>INSS</span></div><div><Image src="/partner-ocpca.png" alt="OCPCA — Ordem dos Contabilistas e Peritos Contabilistas de Angola" width={420} height={260}/><span>OCPCA</span></div></div></div></section>
  <section className="fees"><div><p className="eyebrow">Honorários</p><h2>Uma proposta à medida da sua realidade.</h2></div><div><p>Os honorários são definidos de acordo com a actividade, o nível de exigência e a natureza mensal ou anual dos serviços. Começamos por compreender as necessidades da organização.</p><a className="button" href="#contactos">Solicitar visita gratuita <span>↗</span></a></div></section>
  <section className="faq" id="recursos"><div className="section-head"><p className="eyebrow">Recursos e FAQ</p><h2>Respostas directas para decisões rápidas.</h2></div><div className="faq-list"><details><summary>Que empresas podem trabalhar com a Valory?<span>+</span></summary><p>Micro, pequenas e médias empresas, incluindo negócios comerciais e organizações de serviços.</p></details><details><summary>O serviço pode ser mensal ou anual?<span>+</span></summary><p>Sim. O âmbito é ajustado à necessidade da empresa e pode incluir acompanhamento mensal, trabalhos anuais ou serviços específicos.</p></details><details><summary>A Valory apoia regularizações fiscais?<span>+</span></summary><p>Sim. A equipa apoia no apuramento, regularização, declarações, notificações e acompanhamento perante AGT e INSS.</p></details><details><summary>Como é preparada a proposta comercial?<span>+</span></summary><p>Após um levantamento das necessidades, a proposta considera a actividade, exigência e volume de trabalho da empresa.</p></details></div></section>
  <section className="contact" id="contactos"><div><p className="eyebrow">Vamos conversar</p><h2>Qual é o próximo desafio do seu negócio?</h2><p>Solicite um diagnóstico ou uma visita gratuita. Preencha o formulário e envie o pedido diretamente pelo WhatsApp.</p><a className="whatsapp-inline" href="https://wa.me/244941098302?text=Ol%C3%A1%2C%20Valory!%20Gostaria%20de%20falar%20com%20um%20consultor." target="_blank" rel="noreferrer">WhatsApp: +244 941 098 302 ↗</a></div><form onSubmit={sendWhatsApp}><label>Nome / Empresa<input name="Nome" required placeholder="Como devemos tratar-lhe?"/></label><label>Telefone ou e-mail<input name="Contacto" required placeholder="O seu contacto"/></label><label>Interesse<select name="Interesse"><option>Diagnóstico / visita gratuita</option><option>Contabilidade</option><option>Fiscalidade</option><option>Consultoria financeira</option><option>Formação On-job</option></select></label><label>Mensagem<textarea name="Mensagem" rows={3} placeholder="Conte-nos brevemente o que precisa"/></label><button className="button whatsapp-button" type="submit">Enviar por WhatsApp <span>↗</span></button></form></section>
  <footer><div><Image src="/logo-transparent.png" alt="Valory" width={370} height={210}/><p>Acrescente Valor ao Seu Negócio</p></div><div><small>Morada</small><p>Talatona, Rua do IFAL<br/>Luanda, Angola</p></div><div><small>Contactos</small><p><a href="tel:+244941098302">+244 941 098 302</a><br/><a href="https://wa.me/244941098302" target="_blank" rel="noreferrer">WhatsApp</a><br/><a href="mailto:geral@valory.ao">geral@valory.ao</a></p></div><div><small>Identificação</small><p>NIF 5417257656</p></div><div className="foot-bottom"><span>© {new Date().getFullYear()} Valory, Lda</span><a href="#inicio">Voltar ao topo ↑</a></div></footer>
  <a className="whatsapp-float" href="https://wa.me/244941098302?text=Ol%C3%A1%2C%20Valory!%20Gostaria%20de%20obter%20mais%20informa%C3%A7%C3%B5es." target="_blank" rel="noreferrer" aria-label="Falar com a Valory pelo WhatsApp"><span>WA</span><b>Fale connosco</b></a>
 </main>;
}
